pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/Ramana8713/devops-project.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t demo-app:1.0 app/'
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f k8s/'
      }
    }
  }
}
